# Generated by Django 4.2.7 on 2023-11-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='families',
            name='member',
        ),
    ]
