# Generated by Django 4.2.7 on 2024-05-01 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicApp', '0005_family_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='familyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicApp.families'),
        ),
    ]
