# Generated by Django 4.2.7 on 2024-05-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicApp', '0006_alter_customuser_familyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='memberId',
            field=models.IntegerField(default=0),
        ),
    ]
