# Generated by Django 4.2.7 on 2024-05-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicApp', '0007_alter_transactions_memberid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='memberId',
            field=models.CharField(max_length=255),
        ),
    ]
